# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-14 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='country_id',
            field=models.CharField(max_length=1),
        ),
    ]
