# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-14 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_card', '0003_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tehsil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.CharField(max_length=2)),
                ('tehsil_id', models.CharField(max_length=2)),
                ('tehsil_name', models.CharField(max_length=150)),
            ],
        ),
    ]
