# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-14 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_card', '0005_grampanchayat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grampanchayat',
            name='tehsil_id',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='tehsil',
            name='district_id',
            field=models.CharField(max_length=4),
        ),
    ]
