# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_card', '0009_auto_20170704_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='state_id',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='state',
            name='country_id',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_id',
            field=models.CharField(max_length=2),
        ),
    ]
